### ISSUE TITLE
TODO: fix typos

### ISSUE THREAD

**Issue by wytsai7660** [wytsai7660/OOP-hw2-3_fix#2]
我可以處理，目前發現的有：

| (maybe) typo | fix          |
|--------------|--------------|
| BROCAST_ID   | BROADCAST_ID |
| IoT_devicees | IoT_devices  |
| neigbhors    | neighbors    |
| possitive    | positive     |
| themselv     | themselves   |

@palapapa 你覺得我應該開始處理嗎？

**Comment by palapapa** [comment]
為什麼是從issue 2號開始

wytsai7660 ***@***.***> 於 2024年5月12日 週日 上午3:00 寫道：

**Comment by wytsai7660** [comment]
因為我們有一個pr https://github.com/wytsai7660/OOP-hw2-3_fix/pull/1#issue-2291011897
所以你覺得呢？開修？先擱置？
